### ISSUE TITLE
Error: `value` required in setHeader("SecurityToken", value).

### ISSUE THREAD

**Issue by LwsBtlr** [nfarina/homebridge-liftmaster#13]
I have my lift master setup in home bridge. When I issue a command to open the door, ("Hey Siri, open the Garage Door" I get: `Error: `value` required in setHeader("SecurityToken", value).` In the .err log, and `[Garage Door] Logged in with user ID undefined` in the .log

I have defined the Garage Door in config.json as follows:
`{`
`"accessory": "LiftMaster",`
`          "name": "Garage Door",`
`          "description": "Chamberlain garage door opener",`
`          "username": "user+extension@example.com",`
`          "password": "password"`
`}`

The user+extension@example.com is the email address I have registered with Chamberlain, of course.

**Comment by toolman1** [comment]
I was wondering what the solution is because I have the exact same error/issue and can't find a resolution. Thank you in advance.

**Comment by alexandrupaulpopa** [comment]
Do you have a firewall that inspects the https connections? I had the same issue and i had to disable the inspect for the mac address of the rapsberry pi

**Comment by toolman1** [comment]
Thank you for responding! I do not have anything like that in place. I'm using an Apple AirPort Extreme router, my main machine is an iMac. I can easily connect to my Pi via VNC or Remote Desktop.

**Comment by AppleTechy** [comment]
Out of curiosity what happens if you remove the description like from your
config? Sorry that I probably won't be that much help as I have multiple
garage doors and I didn't have that error. Are you running the newest
version of the plugin? When I had an issue that was similar it was on an
older version that had been used for testing purposes with other issues
that I and some other had.

**Comment by toolman1** [comment]
I don't have a description line in my config.json. I installed:

sudo npm install -g homebridge-liftmaster

Does that not grab the latest version? And if there is a different way to install it, what's the easiest way to remove the old version (I'm still new to this)

Thanks again

**Comment by AppleTechy** [comment]
That should be pulling the newest version.. Have you tried uninstalling the
plugin and then reinstalling? Are you both running it on an RPI?

**Comment by toolman1** [comment]
Yes, a brand new one I just got this morning RPi2 Model B http://www.amazon.com/gp/product/B008XVAVAW

I haven't figured out how to uninstall yet.

One more thing. This is a Craftsman Assurelink garage door opener, which is made by LiftMaster. Is there anything I need to do differently to make it work with Assurelink?

**Comment by AppleTechy** [comment]
Hang on a for a couple minutes. Let me switch over to my computer.  Do I
can review everything. And take a look at the assured link. Are  you on our
slack channel yet?

**Comment by toolman1** [comment]
I'm afraid I'm not, but I'm more than happy to go there if you give me a link!

**Comment by AppleTechy** [comment]
@toolman1 Check the Readme file on the main Homebridge page or use this link[Slack](http://homebridge-slackin.herokuapp.com/)

**Comment by toolman1** [comment]
I'm there now

**Comment by tekuonline** [comment]
@toolman1, sorry i am late but have you looked at assurelink plugin for your assurelink device yet? Its a modified version for assurelink 
https://www.npmjs.com/package/homebridge-assurelink

**Comment by toolman1** [comment]
The one I installed was:

npm install homebridge-assurelink

Are you saying there's a newer version?

**Comment by tekuonline** [comment]
No there is not a updated version, is is working for you with that plugin?

**Comment by toolman1** [comment]
Definitely! Although now I'm using Wink app with the Homebridge Wink plugin
because it gives me HomeKit notifications, whereas if I use the assurelink
plugin it does not.

**Comment by n8man** [comment]
Using node v4.0 on a pi v3:
```
[9/17/2016, 10:03:16 PM] [Garage Door] Logged in with user ID undefined
_http_outgoing.js:333
    throw new Error('`value` required in setHeader("' + name + '", value).');
    ^

Error: `value` required in setHeader("SecurityToken", value).
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:80:14)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:163:15)
    at Request.start (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:914:30)
    at Request.end (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1728:10)
    at end (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:704:14)
    at Immediate._onImmediate (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:718:7)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```
