### ISSUE TITLE
LiftMaster Plugin Failing on status check...

### ISSUE THREAD

**Issue by jacobwtyler** [nfarina/homebridge-liftmaster#22]
I get this string as soon as I check the status of the door in my Home app.  It has something to do with not registering the plugin I believe.  It used to work.  I'm running a systemd daemon if that helps.  I've tried everything I can think of.  Chamberlain plugin gives me a different error which I posted on his site and LiftMaster2 no longer works.  Any help appreciated greatly.  

Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "On"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Got Characteristic "On" value: false
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "On"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Got Characteristic "On" value: false
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "On"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Got Characteristic "On" value: false
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "On"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Got Characteristic "On" value: false
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "On"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Got Characteristic "On" value: false
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "On"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Got Characteristic "On" value: false
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "On"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Got Characteristic "On" value: false
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "On"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Got Characteristic "On" value: true
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "On"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Got Characteristic "On" value: false
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "On"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Got Characteristic "On" value: false
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "BlaBla"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Getting value for Characteristic "On"
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT Accessory [Homebridge Rasp Pi] Got Characteristic "On" value: false
Feb 17 10:49:31 jacobwtyler homebridge[25188]: Fri, 17 Feb 2017 16:49:31 GMT harmonyhubjs:discover:ping emit()
Feb 17 10:49:31 jacobwtyler homebridge[25188]: undefined:1
Feb 17 10:49:31 jacobwtyler homebridge[25188]: <html><head><title>Request Rejected</title></head><body>Your request has been denied.<br><br>[5442595389312380756]</body></html>
Feb 17 10:49:31 jacobwtyler homebridge[25188]: ^
Feb 17 10:49:31 jacobwtyler homebridge[25188]: SyntaxError: Unexpected token <
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at Object.parse (native)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at Request._callback (/usr/local/lib/node_modules/homebridge-liftmaster/index.js:59:25)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at Request.self.callback (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:373:22)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at emitTwo (events.js:87:13)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at Request.emit (events.js:172:7)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1318:14)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at emitOne (events.js:82:20)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at Request.emit (events.js:169:7)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-liftmaster/node_modules/request/request.js:1266:12)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at emitNone (events.js:72:20)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at IncomingMessage.emit (events.js:166:7)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at endReadableNT (_stream_readable.js:905:12)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at nextTickCallbackWith2Args (node.js:437:9)
Feb 17 10:49:31 jacobwtyler homebridge[25188]: at process._tickCallback (node.js:351:17)
Feb 17 10:49:32 jacobwtyler systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Feb 17 10:49:32 jacobwtyler systemd[1]: Unit homebridge.service entered failed state.

**Comment by ghost** [comment]
I am still running the original lift master plugin and it stopped working last week when Chamberlain closed off the 3rd party API's. I'm fortunate that I have an Apple Watch and so the app on it makes it more convenient to be able to open relatively easily, however it's not as easy as home bridge provided. I'm hoping that Chamberlain follows through and releases a home kits capable device in the very near future.

**Comment by michaelwhill** [comment]
just wanted to confirm IF the homebridge-liftmaster plugin no longer works?  I am receiving a similar message when requesting siri open the garage door, the error causes the homebridge application to crash.  Application also crashes when my iOS app checks for the door status, meaning if I start my elgato eve application it checks for status and homebridge crashes.

Request Rejected
Your request has been denied.
[5442595391675xxxxxxx]
